import type { ModelDefinition } from "@/types/model-registry";

/**
 * Static mirror of supabase/migrations/0002_seed_model_registry.sql.
 *
 * The `ai_models` table in Postgres is the source of truth in production —
 * admins can enable/disable/re-prioritize models there without a deploy.
 * This array is the fallback used in tests and any environment where the
 * database has not been reached yet; getModelRegistry() below always
 * prefers the live table.
 */
export const DEFAULT_MODEL_REGISTRY: ModelDefinition[] = [
  {
    id: "wan-2.2",
    name: "Wan 2.2",
    provider: "modal",
    version: "2.2",
    type: "video",
    description: "General-purpose cinematic video model.",
    capabilities: ["text_to_video", "image_to_video", "cinematic_video"],
    minimumVramGb: 24,
    recommendedVramGb: 48,
    supportedResolutions: ["720p", "1080p"],
    supportedFps: [24, 30],
    maximumDurationSeconds: 10,
    inputTypes: ["text", "image"],
    outputTypes: ["video"],
    status: "active",
    enabled: true,
    priority: 10,
    costMultiplier: 1.0,
  },
  {
    id: "skyreels-v2",
    name: "SkyReels V2",
    provider: "modal",
    version: "2",
    type: "video",
    description: "Character-consistent cinematic video model.",
    capabilities: ["character_consistency", "cinematic_video"],
    minimumVramGb: 24,
    recommendedVramGb: 48,
    supportedResolutions: ["720p", "1080p"],
    supportedFps: [24],
    maximumDurationSeconds: 10,
    inputTypes: ["text", "image"],
    outputTypes: ["video"],
    status: "active",
    enabled: true,
    priority: 20,
    costMultiplier: 1.2,
  },
  {
    id: "hunyuan-video",
    name: "HunyuanVideo",
    provider: "modal",
    version: "1",
    type: "video",
    description: "Human performance and motion-focused video model.",
    capabilities: ["human_performance", "text_to_video"],
    minimumVramGb: 40,
    recommendedVramGb: 80,
    supportedResolutions: ["720p", "1080p"],
    supportedFps: [24],
    maximumDurationSeconds: 8,
    inputTypes: ["text"],
    outputTypes: ["video"],
    status: "active",
    enabled: true,
    priority: 30,
    costMultiplier: 1.3,
  },
  {
    id: "cogvideox",
    name: "CogVideoX",
    provider: "modal",
    version: "1",
    type: "video",
    description: "Image-to-video generation model.",
    capabilities: ["image_to_video", "text_to_video"],
    minimumVramGb: 16,
    recommendedVramGb: 24,
    supportedResolutions: ["720p"],
    supportedFps: [8, 16],
    maximumDurationSeconds: 6,
    inputTypes: ["text", "image"],
    outputTypes: ["video"],
    status: "active",
    enabled: true,
    priority: 40,
    costMultiplier: 0.9,
  },
  {
    id: "open-sora",
    name: "Open-Sora",
    provider: "modal",
    version: "1.2",
    type: "video",
    description: "Long-form open video generation model.",
    capabilities: ["text_to_video", "long_form_video"],
    minimumVramGb: 24,
    recommendedVramGb: 48,
    supportedResolutions: ["720p"],
    supportedFps: [24],
    maximumDurationSeconds: 15,
    inputTypes: ["text"],
    outputTypes: ["video"],
    status: "beta",
    enabled: true,
    priority: 50,
    costMultiplier: 1.1,
  },
  {
    id: "ltx-video",
    name: "LTX Video",
    provider: "modal",
    version: "1",
    type: "video",
    description: "Fast low-latency preview video model.",
    capabilities: ["text_to_video", "fast_preview"],
    minimumVramGb: 8,
    recommendedVramGb: 16,
    supportedResolutions: ["480p", "720p"],
    supportedFps: [24, 30],
    maximumDurationSeconds: 5,
    inputTypes: ["text", "image"],
    outputTypes: ["video"],
    status: "active",
    enabled: true,
    priority: 5,
    costMultiplier: 0.5,
  },
  {
    id: "stable-video-diffusion",
    name: "Stable Video Diffusion",
    provider: "modal",
    version: "1.1",
    type: "video",
    description: "Image-to-video diffusion model.",
    capabilities: ["image_to_video"],
    minimumVramGb: 16,
    recommendedVramGb: 24,
    supportedResolutions: ["576p"],
    supportedFps: [7, 25],
    maximumDurationSeconds: 4,
    inputTypes: ["image"],
    outputTypes: ["video"],
    status: "active",
    enabled: true,
    priority: 60,
    costMultiplier: 0.8,
  },
  {
    id: "flux",
    name: "FLUX",
    provider: "modal",
    version: "1",
    type: "image",
    description: "High-fidelity text-to-image model.",
    capabilities: ["text_to_image"],
    minimumVramGb: 16,
    recommendedVramGb: 24,
    supportedResolutions: ["1024p", "2048p"],
    supportedFps: [],
    maximumDurationSeconds: null,
    inputTypes: ["text"],
    outputTypes: ["image"],
    status: "active",
    enabled: true,
    priority: 10,
    costMultiplier: 1.0,
  },
  {
    id: "sdxl",
    name: "Stable Diffusion XL",
    provider: "modal",
    version: "1.0",
    type: "image",
    description: "General-purpose text-to-image model.",
    capabilities: ["text_to_image", "image_to_image"],
    minimumVramGb: 8,
    recommendedVramGb: 16,
    supportedResolutions: ["1024p"],
    supportedFps: [],
    maximumDurationSeconds: null,
    inputTypes: ["text", "image"],
    outputTypes: ["image"],
    status: "active",
    enabled: true,
    priority: 20,
    costMultiplier: 0.7,
  },
  {
    id: "musicgen",
    name: "MusicGen",
    provider: "modal",
    version: "1",
    type: "audio",
    description: "Text-to-music generation model.",
    capabilities: ["text_to_music"],
    minimumVramGb: 8,
    recommendedVramGb: 16,
    supportedResolutions: [],
    supportedFps: [],
    maximumDurationSeconds: 120,
    inputTypes: ["text"],
    outputTypes: ["audio"],
    status: "active",
    enabled: true,
    priority: 10,
    costMultiplier: 1.0,
  },
  {
    id: "audiocraft",
    name: "AudioCraft",
    provider: "modal",
    version: "1",
    type: "audio",
    description: "General audio generation model.",
    capabilities: ["text_to_audio", "sound_effects"],
    minimumVramGb: 8,
    recommendedVramGb: 16,
    supportedResolutions: [],
    supportedFps: [],
    maximumDurationSeconds: 60,
    inputTypes: ["text"],
    outputTypes: ["audio"],
    status: "active",
    enabled: true,
    priority: 20,
    costMultiplier: 1.0,
  },
  {
    id: "stable-audio-open",
    name: "Stable Audio Open",
    provider: "modal",
    version: "1",
    type: "audio",
    description: "Open text-to-audio model.",
    capabilities: ["text_to_music", "text_to_audio"],
    minimumVramGb: 8,
    recommendedVramGb: 16,
    supportedResolutions: [],
    supportedFps: [],
    maximumDurationSeconds: 180,
    inputTypes: ["text"],
    outputTypes: ["audio"],
    status: "active",
    enabled: true,
    priority: 30,
    costMultiplier: 0.8,
  },
  {
    id: "kokoro",
    name: "Kokoro",
    provider: "modal",
    version: "1",
    type: "tts",
    description: "Lightweight fast text-to-speech model.",
    capabilities: ["text_to_speech"],
    minimumVramGb: 2,
    recommendedVramGb: 4,
    supportedResolutions: [],
    supportedFps: [],
    maximumDurationSeconds: null,
    inputTypes: ["text"],
    outputTypes: ["audio"],
    status: "active",
    enabled: true,
    priority: 10,
    costMultiplier: 0.5,
  },
  {
    id: "piper",
    name: "Piper",
    provider: "modal",
    version: "1",
    type: "tts",
    description: "Local-friendly text-to-speech model.",
    capabilities: ["text_to_speech"],
    minimumVramGb: 1,
    recommendedVramGb: 2,
    supportedResolutions: [],
    supportedFps: [],
    maximumDurationSeconds: null,
    inputTypes: ["text"],
    outputTypes: ["audio"],
    status: "active",
    enabled: true,
    priority: 20,
    costMultiplier: 0.4,
  },
  {
    id: "coqui-tts",
    name: "Coqui TTS",
    provider: "modal",
    version: "1",
    type: "tts",
    description: "Multi-speaker text-to-speech model.",
    capabilities: ["text_to_speech", "voice_cloning"],
    minimumVramGb: 4,
    recommendedVramGb: 8,
    supportedResolutions: [],
    supportedFps: [],
    maximumDurationSeconds: null,
    inputTypes: ["text"],
    outputTypes: ["audio"],
    status: "active",
    enabled: true,
    priority: 30,
    costMultiplier: 0.7,
  },
  {
    id: "musetalk",
    name: "MuseTalk",
    provider: "modal",
    version: "1",
    type: "lip_sync",
    description: "Real-time lip-sync model.",
    capabilities: ["lip_sync"],
    minimumVramGb: 8,
    recommendedVramGb: 16,
    supportedResolutions: ["720p"],
    supportedFps: [25],
    maximumDurationSeconds: null,
    inputTypes: ["video", "audio"],
    outputTypes: ["video"],
    status: "active",
    enabled: true,
    priority: 10,
    costMultiplier: 1.0,
  },
  {
    id: "latentsync",
    name: "LatentSync",
    provider: "modal",
    version: "1",
    type: "lip_sync",
    description: "High-fidelity lip-sync diffusion model.",
    capabilities: ["lip_sync"],
    minimumVramGb: 16,
    recommendedVramGb: 24,
    supportedResolutions: ["720p", "1080p"],
    supportedFps: [25],
    maximumDurationSeconds: null,
    inputTypes: ["video", "audio"],
    outputTypes: ["video"],
    status: "beta",
    enabled: true,
    priority: 20,
    costMultiplier: 1.3,
  },
  {
    id: "qwen",
    name: "Qwen",
    provider: "modal",
    version: "2.5",
    type: "llm",
    description: "Script analysis and reasoning LLM.",
    capabilities: ["script_analysis", "reasoning", "prompt_generation"],
    minimumVramGb: 16,
    recommendedVramGb: 24,
    supportedResolutions: [],
    supportedFps: [],
    maximumDurationSeconds: null,
    inputTypes: ["text"],
    outputTypes: ["text"],
    status: "active",
    enabled: true,
    priority: 10,
    costMultiplier: 1.0,
  },
  {
    id: "llama",
    name: "Llama",
    provider: "modal",
    version: "3.1",
    type: "llm",
    description: "General-purpose reasoning LLM.",
    capabilities: ["script_analysis", "reasoning", "prompt_generation"],
    minimumVramGb: 16,
    recommendedVramGb: 24,
    supportedResolutions: [],
    supportedFps: [],
    maximumDurationSeconds: null,
    inputTypes: ["text"],
    outputTypes: ["text"],
    status: "active",
    enabled: true,
    priority: 20,
    costMultiplier: 1.0,
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    provider: "modal",
    version: "3",
    type: "llm",
    description: "Reasoning-focused LLM for script analysis.",
    capabilities: ["script_analysis", "reasoning"],
    minimumVramGb: 16,
    recommendedVramGb: 48,
    supportedResolutions: [],
    supportedFps: [],
    maximumDurationSeconds: null,
    inputTypes: ["text"],
    outputTypes: ["text"],
    status: "active",
    enabled: true,
    priority: 30,
    costMultiplier: 1.0,
  },
];

export function getModelById(id: string): ModelDefinition | undefined {
  return DEFAULT_MODEL_REGISTRY.find((model) => model.id === id);
}
